### ISSUE TITLE
How do you use the cruise,ballistic,and artillery shells

### ISSUE THREAD

**Issue by BiggetyBounceman** [HbmMods/xRadar#1]
you probably don't care about this mod too much, but how do you use the cruise, ballistic, and artillery shells I can use the launch pad to use missiles but not any warheads

**Comment by RagexPrince683** [comment]
I think you need a flans mod pack called Tyrant's and Plebians but don't quote me on that one.

**Comment by BiggetyBounceman** [comment]
Thanks
